language: node_js
sudo: false
node_js:
- '0.10'
addons:
  apt:
    packages:
    - graphicsmagick
before_install:
- npm install bower
- ./node_modules/bower/bin/bower install
after_success:
- ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
env:
  global:
    - secure: YWABlINoIkwl9RFLOW9G0lATEP3aiXXi+DS6TWfvQWWG/jkS5sn7IqWC2U67LjwQ0lDg0yevo3ZD7FyYQ5lr8AVuScAZ6P2o2dm9t/HBKGTG4u016dxbWWYVZ8MAlKT7TfjVD8iDzcWyZedsbpuyaNNp4pGr/CNcvq7TGdJLNkU=
    - CI=1
    - TOLERANCE=0.002
    - DELAY=5000
